# Generated by Django 4.2 on 2023-04-29 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название модели')),
                ('max_load_capacity', models.IntegerField(verbose_name='Максимальная грузоподъёмность')),
            ],
            options={
                'verbose_name': 'Модель самосвала',
                'verbose_name_plural': 'Модели самосвалов',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Tipper',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Бортовой номер')),
                ('current_load_capacity', models.IntegerField(verbose_name='Текущий вес')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistic.modeltipper', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Самосвал',
                'verbose_name_plural': 'Самосвалы',
                'ordering': ['-id'],
            },
        ),
    ]
