# Generated by Django 4.2 on 2023-04-29 13:06

from django.db import migrations

models_tipper = [
    {"name": "БелАЗ", "max_load_capacity": 120},
    {"name": "Komatsu", "max_load_capacity": 110},
]

tippers = [
    ["БелАЗ", {"id": "101", "current_load_capacity": 100}],
    ["БелАЗ", {"id": "102", "current_load_capacity": 125}],
    ["Komatsu", {"id": "K103", "current_load_capacity": 120}],
]


def add_tippers(apps, schema_editor):
    ModelTipper = apps.get_model('logistic', 'ModelTipper')
    Tipper = apps.get_model('logistic', 'Tipper')

    ModelTipper.objects.bulk_create(list(
        ModelTipper(**model) for model in models_tipper
    ))
    Tipper.objects.bulk_create(list(
        Tipper(**tipper, model=ModelTipper.objects.get(name=model_name)) for model_name, tipper in tippers
    ))


def remove_tippers(apps, schema_editor):
    ModelTipper = apps.get_model('logistic', 'ModelTipper')
    Tipper = apps.get_model('logistic', 'Tipper')

    Tipper.objects.filter(id__in=list(tipper["id"] for model, tipper in tippers)).delete()
    ModelTipper.objects.filter(name__in=list(model["name"] for model in models_tipper)).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_tippers, remove_tippers)
    ]
